-- =============================================
-- FULL DATABASE RESET SCRIPT
-- =============================================
-- WARNING: This script will DROP all existing tables and data!
-- Run this on your Render PostgreSQL via pgAdmin, DBeaver, or psql.
-- =============================================

BEGIN TRANSACTION;

-- 1. DROP EXISTING TABLES (Reverse Dependency Order)
DROP TABLE IF EXISTS "invoice_items";
DROP TABLE IF EXISTS "invoices";
DROP TABLE IF EXISTS "payments";
DROP TABLE IF EXISTS "order_items";
DROP TABLE IF EXISTS "orders";
DROP TABLE IF EXISTS "menu_items";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "billiard_sessions";
DROP TABLE IF EXISTS "expenses";
DROP TABLE IF EXISTS "tables";
DROP TABLE IF EXISTS "users";
-- DROP TABLE IF EXISTS "__EFMigrationsHistory"; -- Unnecessary to delete this for app operation

-- 2. CREATE TABLES (Dependency Order)

-- Users
CREATE TABLE "users" (
    "id" uuid NOT NULL,
    "username" character varying(50) NOT NULL,
    "password" character varying(100) NOT NULL,
    "role" character varying(20) DEFAULT 'ADMIN',
    CONSTRAINT "PK_users" PRIMARY KEY ("id")
);

-- Tables
CREATE TABLE "tables" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "table_number" text,
    "name" character varying(50) NOT NULL,
    "alias" character varying(100),
    "guest_name" character varying(100),
    "status" character varying(20) DEFAULT 'Empty',
    "is_occupied" boolean NOT NULL DEFAULT FALSE,
    "current_order_id" uuid,
    CONSTRAINT "PK_tables" PRIMARY KEY ("id")
);

-- Categories
CREATE TABLE "categories" (
    "id" uuid NOT NULL,
    "name" character varying(100) NOT NULL,
    CONSTRAINT "PK_categories" PRIMARY KEY ("id")
);

-- Menu Items
CREATE TABLE "menu_items" (
    "id" uuid NOT NULL,
    "category_id" uuid,
    "name" character varying(200) NOT NULL,
    "price" numeric NOT NULL,
    "image_path" character varying(500),
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "description" text,
    CONSTRAINT "PK_menu_items" PRIMARY KEY ("id"),
    CONSTRAINT "FK_menu_items_categories_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id")
);

-- Orders
CREATE TABLE "orders" (
    "id" uuid NOT NULL,
    "table_id" integer,
    "order_number" integer GENERATED BY DEFAULT AS IDENTITY,
    "status" character varying(20) NOT NULL DEFAULT 'NEW',
    "total_amount" numeric NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone NOT NULL,
    "payment_method" character varying(20),
    "payment_amount" numeric,
    "change_amount" numeric,
    CONSTRAINT "PK_orders" PRIMARY KEY ("id"),
    CONSTRAINT "FK_orders_tables_table_id" FOREIGN KEY ("table_id") REFERENCES "tables" ("id")
);

-- Order Items
CREATE TABLE "order_items" (
    "id" uuid NOT NULL,
    "order_id" uuid NOT NULL,
    "product_id" uuid,
    "product_name" character varying(200),
    "price" numeric NOT NULL,
    "quantity" integer NOT NULL,
    CONSTRAINT "PK_order_items" PRIMARY KEY ("id"),
    CONSTRAINT "FK_order_items_menu_items_product_id" FOREIGN KEY ("product_id") REFERENCES "menu_items" ("id"),
    CONSTRAINT "FK_order_items_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE
);

-- Payments
CREATE TABLE "payments" (
    "id" uuid NOT NULL,
    "order_id" uuid,
    "payment_method" character varying(20) NOT NULL DEFAULT 'cash',
    "amount" numeric NOT NULL,
    "received_amount" numeric,
    "change_amount" numeric,
    "paid_at" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_payments" PRIMARY KEY ("id")
);

-- Expenses
CREATE TABLE "expenses" (
    "id" uuid NOT NULL,
    "description" text NOT NULL,
    "amount" numeric NOT NULL,
    "date" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_expenses" PRIMARY KEY ("id")
);

-- Billiard Sessions
CREATE TABLE "billiard_sessions" (
    "id" uuid NOT NULL,
    "table_id" integer NOT NULL,
    "guest_name" character varying(100) NOT NULL,
    "num_people" integer NOT NULL DEFAULT 2,
    "price_per_hour" numeric NOT NULL,
    "start_time" timestamp with time zone NOT NULL DEFAULT (now()),
    "end_time" timestamp with time zone,
    "total_amount" numeric NOT NULL DEFAULT 0,
    "status" character varying(20) DEFAULT 'ACTIVE',
    CONSTRAINT "PK_billiard_sessions" PRIMARY KEY ("id")
);

-- Invoices
CREATE TABLE "invoices" (
    "id" uuid NOT NULL,
    "table_id" integer NOT NULL,
    "billiard_session_id" uuid,
    "order_id" uuid,
    "total_amount" numeric NOT NULL DEFAULT 0,
    "payment_method" character varying(50) DEFAULT 'cash',
    "identify_string" character varying(200) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_invoices" PRIMARY KEY ("id")
);

-- Invoice Items
CREATE TABLE "invoice_items" (
    "id" uuid NOT NULL,
    "invoice_id" uuid NOT NULL,
    "name" character varying(200) NOT NULL,
    "quantity" integer NOT NULL DEFAULT 1,
    "unit_price" numeric NOT NULL,
    "total_price" numeric NOT NULL,
    "type" character varying(50) DEFAULT 'ITEM',
    CONSTRAINT "PK_invoice_items" PRIMARY KEY ("id"),
    CONSTRAINT "FK_invoice_items_invoices_invoice_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") ON DELETE CASCADE
);

-- 3. SEED DATA

-- Users (Admin Account)
INSERT INTO users (id, username, password, role) VALUES 
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'admin', 'admin123', 'ADMIN'),
('a1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'staff', 'staff123', 'STAFF');

-- Tables
-- Billiard 1-4
INSERT INTO tables (table_number, name, alias, status, is_occupied) VALUES 
('BI-01', 'Bàn Bida 1', 'Bi-a', 'Empty', false),
('BI-02', 'Bàn Bida 2', 'Bi-a', 'Empty', false),
('BI-03', 'Bàn Bida 3', 'Bi-a', 'Empty', false),
('BI-04', 'Bàn Bida 4', 'Bi-a', 'Empty', false);

-- Cafe 1-10
INSERT INTO tables (table_number, name, alias, status, is_occupied) VALUES 
('01', 'Bàn 1', 'Cafe', 'Empty', false),
('02', 'Bàn 2', 'Cafe', 'Empty', false),
('03', 'Bàn 3', 'Cafe', 'Empty', false),
('04', 'Bàn 4', 'Cafe', 'Empty', false),
('05', 'Bàn 5', 'Cafe', 'Empty', false),
('06', 'Bàn 6', 'Cafe', 'Empty', false),
('07', 'Bàn 7', 'Cafe', 'Empty', false),
('08', 'Bàn 8', 'Cafe', 'Empty', false),
('09', 'Bàn 9', 'Cafe', 'Empty', false),
('10', 'Bàn 10', 'Cafe', 'Empty', false);

-- Takeaway
INSERT INTO tables (table_number, name, alias, status, is_occupied) VALUES 
('MV', 'Mang về', 'Takeaway', 'Empty', false);

-- Categories
INSERT INTO categories (id, name) VALUES 
('b1eebc99-9c0b-4ef8-bb6d-6bb9bd380b11', 'Đồ uống'),
('b2eebc99-9c0b-4ef8-bb6d-6bb9bd380b22', 'Đồ ăn'),
('b3eebc99-9c0b-4ef8-bb6d-6bb9bd380b33', 'Dịch vụ');

-- Menu Items
INSERT INTO menu_items (id, category_id, name, price, is_active, description, image_path) VALUES 
('c1eebc99-9c0b-4ef8-bb6d-6bb9bd380c11', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380b11', 'Cà phê đen', 25000, true, 'Black Coffee', ''),
('c2eebc99-9c0b-4ef8-bb6d-6bb9bd380c22', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380b11', 'Cà phê sữa', 30000, true, 'Milk Coffee', ''),
('c3eebc99-9c0b-4ef8-bb6d-6bb9bd380c33', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380b11', 'Sting', 15000, true, 'Energy Drink', ''),
('c4eebc99-9c0b-4ef8-bb6d-6bb9bd380c44', 'b2eebc99-9c0b-4ef8-bb6d-6bb9bd380b22', 'Mì tôm trứng', 35000, true, 'Noodles', ''),
('c5eebc99-9c0b-4ef8-bb6d-6bb9bd380c55', 'b3eebc99-9c0b-4ef8-bb6d-6bb9bd380b33', 'Phí Bida', 50000, true, 'Billiard Fee', '');

COMMIT;
